#coding='utf-8'
#Services列表
serviceList = ['ALL-service','COMMUNITY-CORE-SERVICE','CRM-SERVICE','FINANCE-SERVICE','INV-SERVICE',
               'KOL-SERVICE','MARKETING-ACTIVITY-SERVICE','MESSAGES-SERVICE','MP-CMS-SERVICE',
               'MYACCOUNT-PORTAL-SERVICE','MYACCOUNT-SERVICE','OFFLINE-SHOP-SERVICE','OMNI-CRMHUB-SERVICE',
              'OMNI-MEMBER-MSG-SERVICE','OMNI-ORDERCENTER-SERVICE',
               'ORDER-SERVICE','PIM-BACKEND',
               'PRODUCT-SERVICE','PROMOTION-SERVICE','SEARCH-SERVICE',
               'SHOP-CART-SERVICE','SOA-MANAGEMENT','OMS-SERVICE','WCS-SERVICE','WECHATCENTER-SERVICE']



